name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - uses: actions/checkout@v4

      # 2. Install JDK 17 on the runner
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Install Gradle 8.7 (no wrapper needed)
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.7

      # 4. Build the debug APK
      - run: gradle assembleDebug

      # 5. Upload the generated APK
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hawaii-widget-debug
          path: app/build/outputs/apk/debug/*.apk
